// Types for importing image files, as `src/lib/gallery.ts` does.
//
// Next writes these same declarations into next-env.d.ts, but that file is
// generated by `next dev` or `next build` and is git-ignored, so `tsc --noEmit`
// on a fresh checkout has nothing to go on. Declaring the reference here keeps
// the typecheck step working before any build has run, which is the order CI
// uses.
/// <reference types="next/image-types/global" />
